### PR TITLE
generalTab.py:Adding the necessary comments to increase code readability

### PR DESCRIPTION
**Pull request by jayantsaraf**
necessary comments are added in generalTab.py to increase code readability 

Fixes  321

### CODE REVIEW

**Comment by abhsag24** [comment]
Hi thank you for your Patch make sure you have the right commit structure that is 
```
tag: Shortlog

body
Fixes <issue number/url>
```
Also please upload a screenshot if you have made changes to the gui.

**Comment by jayantsaraf** [comment]
@abhsag24  can you please help in solving the above issue?

**Comment by nkprince007** [comment]
He's a bit caught up at the moment.. please contact in the gitter channel if you need further assistance.

**Comment by jayantsaraf** [comment]
@nkprince007  okay thanks

**Comment by abhsag24** [comment]
Hey! This wasn't updated since a while. Please check up on it!

**Comment by abhsag24** [comment]
Hey! This wasn't updated since a while. Please check up on it!

**Comment by abhsag24** [comment]
Hey! This wasn't updated since a while. Please check up on it!

**Comment by abhsag24** [comment]
Hey! This wasn't updated since a while. Please check up on it!

**Comment by abhsag24** [comment]
Hey! This wasn't updated since a while. Please check up on it!

**Comment by abhsag24** [comment]
Hey! This wasn't updated since a while. Please check up on it!

**Comment by abhsag24** [comment]
Hey! This wasn't updated since a while. Please check up on it!

**Comment by abhsag24** [comment]
Hey! This wasn't updated since a while. Please check up on it!

**Comment by abhsag24** [comment]
Hey! This wasn't updated since a while. Please check up on it!

**Comment by abhsag24** [comment]
Hey! This wasn't updated since a while. Please check up on it!

**Comment by abhsag24** [comment]
Hey! This wasn't updated since a while. Please check up on it!

**Comment by abhsag24** [comment]
Hey! This wasn't updated since a while. Please check up on it!

**Comment by abhsag24** [comment]
Hey! This wasn't updated since a while. Please check up on it!

**Comment by abhsag24** [comment]
Hey! This wasn't updated since a while. Please check up on it!

**Comment by abhsag24** [comment]
Hey! This wasn't updated since a while. Please check up on it!

**Comment by abhsag24** [comment]
Hey! This wasn't updated since a while. Please check up on it!

**Comment by abhsag24** [comment]
Hey! This wasn't updated since a while. Please check up on it!

**Comment by abhsag24** [comment]
Hey! This wasn't updated since a while. Please check up on it!

**Comment by abhsag24** [comment]
Hey! This wasn't updated since a while. Please check up on it!

**Comment by abhsag24** [comment]
Hey! This wasn't updated since a while. Please check up on it!

**Comment by abhsag24** [comment]
Closing as too old

**Pull request closed without merging**
