### PR TITLE
Remove GUI entirely

### PR DESCRIPTION
**Pull request by abhsag24**
Fixes https://github.com/NITDgpOS/UIP/issues/374

### CODE REVIEW

**Comment by Aniq55** [comment]
Removing GUI? :scream:  @abhsag24

**Comment by abhsag24** [comment]
yup @Aniq55 after we merge this we will work on adding features from the gui, like blur to the main uip

**Comment by Aniq55** [comment]
I'll create a new branch `gui` from `master` and then merge this to `master` so that the gui version is also preserved. @abhsag24

**Comment by abhsag24** [comment]
Sure that sounds fair though it is preserved in commits anyway you, can
always fork from that commit if you want

**Comment by Aniq55** [comment]
@abhsag24 I didn't know that. In that case there is no need to create a branch for `gui`

**Comment by nkprince007** [comment]
ack https://github.com/NITDgpOS/UIP/pull/376/commits/2484ceb220b20553de021c3f40f2654002f56143

**Comment by abhsag24** [comment]
reack 7b28df8

**Pull request merged**
